### ISSUE TITLE
Setup instructions not working

### ISSUE THREAD

**Issue by planetahuevo** [tierpod/dmarc-report-converter#13]
I am trying to follow the instructions and I cannot get the first line to work:

download pre-builded archive from releases or build dmarc-report-converter executable:

go get -u github.com/tierpod/dmarc-report-converter
cd $HOME/go/src/github.com/tierpod/dmarc-report-converter
make bin/dmarc-report-converter
now you can run ./bin/dmarc-report-converter and test it

**Comment by planetahuevo** [comment]
Find out how to do it. :)

**Comment by tierpod** [comment]
Hello @planetahuevo ! What kind of problem did you have? If you give me more information I will try to improve documentation or installation process.

**Comment by planetahuevo** [comment]
Hi, Let me wrote it here:
- First, if your server is new, you may need to have go installed. 
so in my case: 
`sudo apt  install golang-go`
After that this command didn´t work: 
` go get -u github.com/tierpod/dmarc-report-converter`
not sure why, so I downloaded master and uploaded myself to the home folder
`cd $HOME/yourfolder/dmarc-report-converter-master `
then we can execute this from the root of the master folder, where the makefile is.
`make bin/dmarc-report-converter`
That will generate a bin folder on the same one. 
Then Steps 2-4 are right, and you can use `make install` for that, but you can have permissions problems and then it does not work as expected. Also the make install won´t rename the config file.
So new steps will be (I do not think `make install` makes this easier).
- copy bin/dmarc-report-converter executable to installation directory (for example, /opt/dmarc-report-converter)  `cp bin/dmarc-report-converter /opt/dmarc-report-converter`
- copy config/config.dist.yaml to installation directory, rename and edit it
```
cp config/config.dist.yaml /opt/dmarc-report-converter/config.yaml
nano /opt/dmarc-report-converter/config.yaml
```
- copy templates directory to installation directory
`cp templates /opt/dmarc-report-converter/`

And then edit assets and destination, but that is ok on your instructions if people know how to setup a webserver. Maybe a link to nginx for the ones that do not?
Also the config line commented with the long name does not work properly (I think, I edited, but I think something is not right there).

**Comment by tierpod** [comment]
Documentation has updated in the branch issue#13, could you read it?

**Comment by planetahuevo** [comment]
I can. It is fantastic! Thanks!
