### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by coolaj86** [tierpod/dmarc-report-converter#17]
Just wanted to say thanks. My day is better because of you. 👍

**Comment by tierpod** [comment]
You are welcome! :smile: I'm pleased to hear good review.

**Comment by elandorr** [comment]
Same here, thanks! This gives a quick overview without needing a huge setup. Super simple to use.

Suggestion: Aggregation across providers, so it's apparent whether there's some problem or not. (9/10 times there's nothing, after all)
