### ISSUE TITLE
Now option not working

### ISSUE THREAD

**Issue by jwnetwerk** [tierpod/dmarc-report-converter#25]
I tried the line specified above. This gives the error: 

panic: template: filename:1: function "now" not defined

goroutine 1 [running]:
html/template.Must(...)
        /opt/hostedtoolcache/go/1.13.15/x64/src/html/template/template.go:372
main.loadConfig(0x7ffd72018763, 0xd, 0x2, 0x2, 0x0)
        /home/runner/work/dmarc-report-converter/dmarc-report-converter/cmd/dmarc-report-converter/config.go:103 +0x5fc
main.main()
        /home/runner/work/dmarc-report-converter/dmarc-report-converter/cmd/dmarc-report-converter/main.go:30 +0x1a6[ERROR] loadConfig: yaml: line 20: did not find expected key

_Originally posted by @jwnetwerk in https://github.com/tierpod/dmarc-report-converter/issues/23#issuecomment-1032675966_

**Comment by tierpod** [comment]
@jwnetwerk this function was only available in the master branch.

I released v0.6.1 with this "now" function, please update your installation and it should work fine.

**Comment by jwnetwerk** [comment]
Yes, It is working now. Thanks!
