### ISSUE TITLE
Created a Docker Compose wrapper

### ISSUE THREAD

**Issue by nielsbom** [tierpod/dmarc-report-converter#59]
Hi,

Not sure how to contact you/y'all so here's an "issue".
I made a Docker Compose wrapper around dmarc-report-converter to make it easier for myself to generate and view reports on my local machine: https://github.com/nielsbom/dmarc_report_viewer

I've only tested this on my arm64 Apple hardware and using [OrbStack](https://orbstack.dev/) so not sure if/how it works on other hardware, OS'es or container tech.

Feel free to close this issue or link to it from this repo's README.

And most importantly **thank you** for making this tool!

**Comment by tierpod** [comment]
This is really cool, thank you! I'll link to your repo

**Comment by tierpod** [comment]
v0.8.0 released #61
